wire: fix race conditions with simultaneous wires
Invariant `NoOverdrafts` violations:
```
Error: Invariant NoOverdrafts is violated.
   Error: The behavior up to this point is:
State 1: <Initial predicate>
/\ people = {"alice", "bob"}
/\ sender = <<"alice", "alice">>
/\ receiver = <<"bob", "bob">>
/\ acc = [alice |-> 5, bob |-> 5]
/\ amount = <<1, 5>>
/\ pc = <<"CheckFunds", "CheckFunds">>

State 2: <CheckFunds line 51, col 21 to line 55, col 76 of module wire>
/\ people = {"alice", "bob"}
/\ sender = <<"alice", "alice">>
/\ receiver = <<"bob", "bob">>
/\ acc = [alice |-> 5, bob |-> 5]
/\ amount = <<1, 5>>
/\ pc = <<"Withdraw", "CheckFunds">>

State 3: <CheckFunds line 51, col 21 to line 55, col 76 of module wire>
/\ people = {"alice", "bob"}
/\ sender = <<"alice", "alice">>
/\ receiver = <<"bob", "bob">>
/\ acc = [alice |-> 5, bob |-> 5]
/\ amount = <<1, 5>>
/\ pc = <<"Withdraw", "Withdraw">>

State 4: <Withdraw line 57, col 19 to line 60, col 69 of module wire>
/\ people = {"alice", "bob"}
/\ sender = <<"alice", "alice">>
/\ receiver = <<"bob", "bob">>
/\ acc = [alice |-> 4, bob |-> 5]
/\ amount = <<1, 5>>
/\ pc = <<"Deposit", "Withdraw">>

State 5: <Withdraw line 57, col 19 to line 60, col 69 of module wire>
/\ people = {"alice", "bob"}
/\ sender = <<"alice", "alice">>
/\ receiver = <<"bob", "bob">>
/\ acc = [alice |-> -1, bob |-> 5]
/\ amount = <<1, 5>>
/\ pc = <<"Deposit", "Deposit">>
```

State #1: Both Process1 and Process2 are ready to check funds.

State #2: Process1 is ready to withdraw funds while Process2 is ready
to check funds.

State #3: Both Process1 and Process2 are ready to withdraw funds.

State #4: Process1 successfully withdraws 1$ from alice's account and
ready to deposit into bob's account while Process2 is ready to withdraw
5$ from alice's account.

State #5: Process1 is ready to deposity into bob's account while Process2
successfully withdraws 5$ from alice's account violating `NoOverdrafts`
invariant.

The failure is due to race condition between check finds and withdrawl. We
fix the problem but comining check funds and withdrawl into one atomic step.